apiVersion: v1
kind: Service
metadata:
  labels:
    app: oauth2-deploy-demo
  name: oauth2-deploy-demo
  namespace: tooling
spec:
  type: ExternalName
  externalName: oauth2-deploy-demo.osc-fr1.scalingo.io
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-deploy-demo
  namespace: tooling
  labels:
    app: oauth2-deploy-demo
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/upstream-vhost: oauth2-deploy-demo.osc-fr1.scalingo.io
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/compute-full-forwarded-for: "true"
    nginx.ingress.kubernetes.io/client-max-body-size: 20M
    nginx.ingress.kubernetes.io/proxy-body-size: 20M
    nginx.ingress.kubernetes.io/use-real-ip: "true"
    nginx.ingress.kubernetes.io/proxy-real-ip-cidr: "0.0.0.0/0"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
spec:
  rules:
    - host: oauth2-deploy-demo.kube-dev.incubateur.net
      http:
        paths:
          - backend:
              service:
                name: oauth2-deploy-demo
                port:
                  name: https
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - oauth2-deploy-demo.kube-dev.incubateur.net
      secretName: oauth2-deploy-demo-proxy
      
